name: therandy
version: stable
version-script: git -C parts/therandy/build describe --abbrev=0 --tags
summary: Magnificent app which corrects your previous console command.
description: |
  The Randy tries to match a rule for the previous command,
  creates a new command using the matched rule and runs it.

grade: stable
confinement: classic

apps:
  therandy:
    command: bin/therandy
    environment:
        PYTHONIOENCODING: utf-8
  randy:
    command: bin/randy
    environment:
        PYTHONIOENCODING: utf-8

parts:
  therandy:
    source: https://github.com/benmonro/therandy.git
    plugin: python
